'\" t
.\"     Title: keepassxc-rofi
.\"    Author: Gary Tierney
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: v0.1
.\"    Manual: EVE
.\"    Source: EVE
.\"  Language: English
.\"
.TH "KEEPASSXC\-ROFI" "1" "v0\&.1" "EVE" "EVE"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
keepassxc-rofi \- show a graphical prompt with a listing of KeePassXC entries to be copied to the clipboard\&.
.SH "SYNOPSIS"
.sp
\fBkeepassxc\-rofi\fR [\fIOPTION\fR]\&...
.SH "ENVIRONMENT VARIABLES"
.PP
\fBPASSWORD_DATABASE\fR
.RS 4
Path to a KeePassXC password database\&.
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success\&. Password was copied to the clipboard\&.
.RE
.PP
\fB1\fR
.RS 4
Failure\&. Could not open
\fBPASSWORD_DATABASE\fR
with the password entered\&.
.RE
.SH "RESOURCES"
.sp
\fBProject web site:\fR https://github\&.com/garyttierney/keepassxc\-rofi
.SH "COPYING"
.sp
Copyright \(co 2019 Gary Tierney\&. Free use of this software is granted under the terms of the ISC License\&.
.SH "AUTHOR"
.PP
\fBGary Tierney\fR
.RS 4
Author.
.RE
