#!/bin/sh
# -*- mode: sh -*-
# vi: set ft=sh :

__error() {
    if [ -t 1 ]; then
        echo "$1" >&2
    else
        zenity --error "$1"
    fi

    exit 1
}

__keepassxc_cli_secure() {
    if [ -z "$1" ]; then
        __error "__keepassxc_cli_secure: No key id present"
    fi

    KEY_ID_ARG="$1"
    shift

    if [ $# -eq 0 ]; then
        __error "__keepassxc_cli_secure: No keyctl arguments present"
    fi

    keyctl pipe "$KEY_ID_ARG" | keepassxc-cli "$@" 2>&1
    unset -v KEY_ID_ARG
}

# shellcheck source=config/keepassxc-rofirc.example
[ -f "$HOME/.keepassxc-rofirc" ] && . "$HOME/.keepassxc-rofirc"

if [ -z "$PASSWORD_DATABASE" ]; then
    __error "keepassxc-rofi: No password database configured"
fi

if [ -z "$PASSWORD_CACHE_TIMEOUT" ]; then
    PASSWORD_CACHE_TIMEOUT=7200
fi

DATABASE_ID=$(printf "%s" "$PASSWORD_DATABASE" | sha256sum)
KEY_DESC="keepassxc:$DATABASE_ID"
KEY_ID=$(keyctl search @s user "$KEY_DESC" 2> /dev/null)

if [ $? -ne 0 ]; then
    KEY_ID=$(rofi -dmenu -i -p "Enter your database password" -l 0 -password -width 500 | keyctl padd user "$KEY_DESC" @s)

    if ! keyctl timeout "$KEY_ID" "$PASSWORD_CACHE_TIMEOUT"; then
        __error "keepassxc-rofi: Unable to cache password in keyring"
    fi
fi

PASS_ID=$(__keepassxc_cli_secure "$KEY_ID" ls -q -R "$PASSWORD_DATABASE" \
    | awk '
            BEGIN {
                FS = "  "
                GROUP_STACK[0] = ""
                GROUP_STACK_POS = 0
                LAST_GROUP_DEPTH = -1
            }

            {
                GROUP_DEPTH = NF - 1;
                TRAILING = substr($0, length($0));

                if (TRAILING == "/" && GROUP_DEPTH > LAST_GROUP_DEPTH) {
                    GROUP_STACK_POS++;
                } else if (GROUP_DEPTH < LAST_GROUP_DEPTH) {
                    GROUP_STACK_POS = GROUP_STACK_POS - LAST_GROUP_DEPTH - GROUP_DEPTH + 1;
                }

                # print "DEPTH " GROUP_DEPTH " LAST_DEPTH " LAST_GROUP_DEPTH " GROUP_STACK_POS " GROUP_STACK_POS  " " $NF

                if (TRAILING == "/") {
                    GROUP_STACK[GROUP_STACK_POS] = sprintf("%s%s", GROUP_STACK[GROUP_STACK_POS - 1], $NF);
                } else if ($NF != "[empty]") {
                    PREFIX = GROUP_STACK[GROUP_STACK_POS];
                    print PREFIX $NF;
                }

                LAST_GROUP_DEPTH = GROUP_DEPTH;
            }
          ' \
    | rofi -dmenu -i -20 -p "Select a password entry")

if [ -n "$PASS_ID" ]; then
    __keepassxc_cli_secure "$KEY_ID" clip -q "$PASSWORD_DATABASE" "$PASS_ID"
    notify-send "Copied password to clipboard" "$PASS_ID is available on the clipboard for 10 seconds"
    sleep 10

    if  __keepassxc_cli_secure "$KEY_ID" clip -q -t "$PASSWORD_DATABASE" "$PASS_ID"; then
        notify-send "Copied OTP to clipboard" "OTP code for $PASS_ID is available on the clipboard for 10 seconds"
    fi
fi
